---
mail_dovecot_storage_user: vmail
mail_dovecot_storage_group: vmail

# These should be < 1000 (system user), and something that is usually unused.
mail_dovecot_storage_uid: 525
mail_dovecot_storage_gid: 525

mail_dovecot_storage_user_home: /var/mail
mail_dovecot_storage_base_dir: /var/mail/virtual
mail_dovecot_storage_static_accounts_dir:
  '{{ mail_dovecot_storage_base_dir }}/static'
mail_dovecot_storage_admin_account_dir:
  '{{ mail_dovecot_storage_static_accounts_dir }}/admin'
mail_dovecot_storage_dynamic_accounts_dir:
  '{{ mail_dovecot_storage_base_dir }}/dynamic'


mail_dovecot_admin_address: 'postmaster@{{ mail_default_domain }}'

# See `/ansible/roles/mail/dovecot/templates/dovecot/auth.conf.j2`.
mail_dovecot_group_account_separator: '*'


mail_dovecot_conf_aux_dir: /etc/dovecot/extra

mail_dovecot_sysctl_conf_path: /etc/sysctl.d/50-dovecot-custom.conf
...
