---
# Network configuration using ifupdown.
#  * Note that this does not configure resolv.conf (DNS).
#    - See the `common/dnssec-resolver` role.


- name: Install ifupdown
  ansible.builtin.apt:
    name: ifupdown
    state: present


- name: Install & configure DHCP client
  ansible.builtin.include_tasks: dhcp.yaml


- name: Configure firewall for DHCP
  ansible.builtin.copy:
    src: dhcp.nft
    dest: '{{ nftables_custom_conf_dir }}/dhcp.nft'
    owner: root
    group: root
    mode: '0644'
  notify:
    - 'common/firewall : Reload nftables'


- name: Configure ifupdown
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    validate: "ifup --all --no-act --force --interfaces='%s'"
  notify:
    - 'common/network : Restart ifupdown'
...
