---
pkgs_tools: '{{ pkgs_tools_standard + pkgs_tools_extra | unique }}'

pkgs_tools_standard:

  # Documentation.
  - man-db
  - manpages
  - info

  # Network tools.
  - iputils-ping
  - netcat-openbsd    # Unlike netcat-traditional, supports sockets (i.a.).
  - ldnsutils         # `drill`
  - nload
  - whois
  - curl
  - wget

  # Finding stuff.
  - findutils         # (Priority: required)
  - mlocate

  # Calculators.
  - dc
  - bc

  # Editors.
  - ed
  - vim
  - vim-scripts

  # Partitioning
  - parted
  - fdisk
  - gdisk

  # Miscellaneous tools.
  - bash-completion
  - screen
  - less
  - file
  - lsof
  - sed
  - libarchive-tools  # `bsdtar`
...
