---
# General info w.r.t. the deployed instance of this software.

product_url_imprint: https://www.law-orga.de/internal/imprint/
product_url_privacy_policy: https://home.refugeelawclinics.de/privacy-policy/
product_url_code_mail: https://github.com/lawandorga/lawandorga-mail-server
...
