---
- name: mlocate - Disable pruning by filename
  ansible.builtin.replace:
    path: /etc/updatedb.conf
    regexp: '^(PRUNENAMES=.*)$'
    replace: '#\1'


- name: mlocate - Configure prune paths
  ansible.builtin.lineinfile:
    path: /etc/updatedb.conf
    regexp: '^PRUNEPATHS=.*'
    line: 'PRUNEPATHS="{{ mlocate_prunepaths }}"'
...
