---
# Configuration files for Dovecot itself.


- name: Install main Dovecot configuration file
  ansible.builtin.template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - 'mail/dovecot : Reload Dovecot'


- name: Create directory for auxiliary configuration files
  ansible.builtin.file:
    path: '{{ mail_dovecot_conf_aux_dir }}'
    owner: root
    group: root
    mode: '0755'
    state: directory
    follow: no


- name: Install auxiliary configuration files
  ansible.builtin.template:
    src: 'dovecot/{{ item }}.j2'
    dest: '{{ mail_dovecot_conf_aux_dir }}/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - services.conf
    - tls.conf
    - auth.conf
    - logging.conf
    - mail-storage.conf
    - mailboxes.conf
    - lmtp.conf
    - imap.conf
  notify:
    - 'mail/dovecot : Reload Dovecot'


# Access.
#  - Dovecot's $default_internal_user (`dovecot`) needs read access.
#  - Restrict access mode.
#    - This should not be necessary.
#      - The file does not contain a (valid) password (hash), despite its name.
#    - This is to avoid future mistakes, where passwords are configured within
#      without restricting the mode here.
- name: Configure static accounts
  ansible.builtin.template:
    src: dovecot/static-users.passwd.j2
    dest: '{{ mail_dovecot_conf_aux_dir }}/static-users.passwd'
    owner: dovecot
    group: dovecot
    mode: '0400'
  notify:
    - 'mail/dovecot : Reload Dovecot'


# These files contains the SQL password; thus, the access needs restricting.
- name: Configure SQL queries
  ansible.builtin.template:
    src: 'dovecot/{{ item }}.j2'
    dest: '{{ mail_dovecot_conf_aux_dir }}/{{ item }}'
    owner: root
    group: root
    mode: '0600'
  with_items:
    - sql-common.conf.ext
    - sql-adminauth.conf.ext
    - sql-groupauth.conf.ext
  notify:
    - 'mail/dovecot : Reload Dovecot'
...
