---
# Configure mail storage, with its own user and group.
#  * The mail storage needs an owner with a static uid:gid s.t. a rebuild of
#    the system can work with the old mail data.
#    * See also `/ansible/roles/mail/postfix/tasks/opendkim.yaml`.


- name: Configure mail storage group
  ansible.builtin.group:
    name: '{{ mail_dovecot_storage_group }}'
    gid: '{{ mail_dovecot_storage_gid }}'
    system: yes


- name: Configure mail storage user
  ansible.builtin.user:
    name: '{{ mail_dovecot_storage_user }}'
    uid: '{{ mail_dovecot_storage_uid }}'
    group: '{{ mail_dovecot_storage_group }}'
    home: '{{ mail_dovecot_storage_user_home }}'
    create_home: no
    shell: /usr/sbin/nologin
    system: yes


- name: Create mail storage directories
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ mail_dovecot_storage_user }}'
    group: '{{ mail_dovecot_storage_group }}'
    mode: '0700'
    state: directory
    follow: no
  with_items:
    - '{{ mail_dovecot_storage_base_dir }}'
    - '{{ mail_dovecot_storage_static_accounts_dir }}'
    - '{{ mail_dovecot_storage_dynamic_accounts_dir }}'


- name: Configure backup
  ansible.builtin.template:
    src: backup.conf.bash.j2
    dest: '{{ backup_config_dir }}/mail-storage.conf.bash'
    owner: root
    group: root
    mode: '0644'
...
