---
- name: Force certificate update (staging)
  ansible.builtin.command:
    argv:
      - '{{ tls_acme_script_path }}'
      - '--force-new'

# Note:
#  * This handler should always be notified in tandem with
#    "Force certificate update (staging)".
#    - We want to test any change to our configuration in the staging
#      enviroment first.
#      - Notably, this helps avoid hitting the rate limits.
#    - The order these handlers are defined in ensures they are run in the
#      correct order.
- name: Force certificate update
  ansible.builtin.command:
    argv:
      - '{{ tls_acme_script_path }}'
      - '--production'
      - '--force-new'
...
