---
# This is largely, but not fully, server-agnostic.  (culprit: /var/mail)
#  - One might want to use the ansible.posix.mount module instead.
#    - Problem: We also need the fstab at setup time.
fstab_file: ../conf/fstab

# This is currently server-agnostic, but that will likely change.
hosts_template: ../conf/hosts.j2
...
