---
# Note:
#  * There is additionally an undeclared mutual dependency between
#    `mail/dovecot` and `mail/postfix`.
#    - This role's dependency on `mail/postfix` is due to its using the
#      `postfix` user.
#      - See `templates/dovecot/services.conf.j2`.
#    - See also `/ansible/roles/mail/tasks/main.yaml`.


dependencies:
  - role: mail/common
  - role: database-access
  - role: tls/key
  - role: tls/acme
  - role: backup
  - role: common/firewall
  - role: common/systemd    # We use a handler from there.

  # See <https://doc.dovecot.org/configuration_manual/os/>.
  - role: common/ntp-client
...
