---
# Unmask systemd unit associated with a package.
#  - See `tasks/apt-systemd-noautostart-pre.yaml`.


- name: 'Unmask units for {{ mask_package_name }}'
  ansible.builtin.systemd:
    name: '{{ item }}'
    masked: no
  loop: '{{ mask_systemd_units }}'
...
