---
# Roundcube Webmail.


# This should come before installation of `roundcube`.
#  * Note: This applies to Debian Bookworm and is deemed not unlikely to change
#    in later releases.
#  - This satisfies a dependency of `roundcube-core`.
#    - This installs `php-fpm`.
#    - `roundcube-core` has a dependency on `php`, which is effectively
#      satisfied by `php-fpm`, and would otherwise pull in
#      `libapache2-mod-php`.
#    - Note that if installing `php-fpm` at the same time as `roundcube` /
#      `roundcube-core`, the former must be listed before the latter, to avoid
#      pulling in the extra dependency.
#  - This allows us to use {{ web_app_mail_php_version }} in the following.
- name: Install & configure PHP
  ansible.builtin.include_tasks: php.yaml


- name: Install Roundcube
  ansible.builtin.apt:
    name:
      - roundcube

      # Install at the same time to avoid pulling the default dependency
      # roundcube-mysql (dependency of roundcube-core).
      - roundcube-pgsql

      # This notably contains the dovecot_impersonate plugin.
      - roundcube-plugins-extra

      # Extra skin (default `elastic`).
      #  - We intentionally do not install the `classic` skin.
      #    - See `../templates/roundcube.conf.php.j2` on why.
      - roundcube-skin-larry

    state: present


- name: Create script directory
  ansible.builtin.file:
    path: '{{ web_app_mail_script_dir }}'
    owner: root
    group: root
    mode: '0755'
    state: directory
    follow: no


- name: Install spelling software
  ansible.builtin.apt:
    name: '{{ [ "php-pspell" ] + aspell_packages }}'
  vars:
    aspell_packages:
      "{{ web_app_mail_aspell_languages | map('regex_replace', '^', 'aspell-') | list }}"


- name: Configure Roundcube
  ansible.builtin.template:
    src: roundcube.conf.php.j2
    dest: /etc/roundcube/config.inc.php
    owner: www-data
    group: www-data
    mode: '0400'    # Protect database password.


- name: Configure random key
  ansible.builtin.shell:
    # The string must be 24 characters long (6 * 24 = 8 * 18).
    cmd: umask 077;
      printf "<?php\\n\$config['des_key'] = '%s';\\n"
      "$(head -c 18 /dev/urandom | base64)"
      > '{{ web_app_mail_keyconfig_path }}'
    creates: '{{ web_app_mail_keyconfig_path }}'


- name: Restrict access to key
  ansible.builtin.file:
    path: '{{ web_app_mail_keyconfig_path }}'
    owner: www-data
    group: www-data
    mode: '0400'
    state: file
    follow: no


# Notes
#  * It is also possible to install several About pages, for several languages,
#    named, e.g., `/etc/roundcube/about.EN.html`.
#  * This is used to display legal links.
#  * See also
#    `roles/web/app/mail/templates/roundcube.conf.php.j2#skins_allowed`.
- name: Configure About page
  ansible.builtin.template:
    src: about.html.j2
    dest: /etc/roundcube/about.html
    owner: root
    group: root
    mode: '0644'


- name: Configure dovecot_impersonate plugin
  ansible.builtin.template:
    src: plugins/dovecot_impersonate/config.inc.php.j2
    dest: /etc/roundcube/plugins/dovecot_impersonate/config.inc.php
    owner: root
    group: root
    mode: '0644'


- name: Install dovecot_impersonate_smtp plugin
  ansible.builtin.include_tasks: plugins/dovecot_impersonate_smtp.yaml


- name: Install login_page_extra_links plugin
  ansible.builtin.include_tasks: plugins/login_page_extra_links.yaml


# Ensure the connection to the database is set up.
- name: Flush handlers
  ansible.builtin.meta: flush_handlers


- name: Initialize database
  ansible.builtin.include_tasks: database.yaml


- name: Set up deletion of old userdata
  ansible.builtin.include_tasks: delete-old-userdata.yaml


- name: Configure Nginx for Roundcube
  ansible.builtin.template:
    src: nginx-roundcube.server.conf.j2
    dest: '{{ web_core_http_confdir_implicit_servers_regular }}/roundcube.server.conf'
    owner: root
    group: root
    mode: '0644'
  notify:
    - 'web/core/http : Reload nginx'


# See crontab(5) for crontab syntax.
- name: Configure cron to send mail to root
  ansible.builtin.lineinfile:
    path: /etc/cron.d/roundcube-core
    regexp: '^MAILTO *='
    insertbefore: '^[ \t]*[0-9@]'  # "cron commands"
    firstmatch: yes                # insert before first match
    line: 'MAILTO=root'
...
