---
# systemd configuration.


- name: Install systemd
  ansible.builtin.apt:
    name:
      # Depends on `systemd-sysv`:
      - init

      # Recommended by `systemd-sysv`.
      # package desc.: "If in doubt, do install this package."
      - libpam-systemd

    state: present


- name: Configure journald
  ansible.builtin.template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - 'common/systemd : Restart journald'
...
