---
# (PostgreSQL) database settings.
#  - See `/doc/database.md`, `/ansible/hosts.yaml`.

database_server_address: '{{ network.private_db.ipv4.db.address }}'
database_server_port: '{{ network.private_db.ipv4.db.port }}'
database_user: lawandorga-mail-server
database_password: '{{ secret_database_password }}'

database_name_mail: lawandorga-backend
...
