---
fqdn: mail.law-orga.de

# This is largely, but not fully, server-agnostic.  (culprit: /var/mail)
#  - One might want to use the ansible.posix.mount module instead.
#    - Problem: We also need the fstab at setup time.
fstab_file: ../conf/fstab

# See `./mail.yaml#mail_admin_alias_localparts_extra`.
tls_acme_contacts:
  - 'mailto:acme@{{ mail_default_domain }}'

tls_acme_domain_names: '{{ [ fqdn, webmail_domain ] | unique }}'
...
