---
# Server specific mail configuration.


# Memory.
#  - See `/ansible/roles/mail/dovecot/templates/services.conf.j2`.
#  - We cannot set this in the role vars, because that should be agnostic
#    w.r.t. the available server memory.
mail_dovecot_auth_memory_limit: 2G


# This should generally not be changed once established.
#  - Do not use the {{ fqdn }} variable here, which may change with aguably
#    less implications.
#    - Note, however, that the {{ mail_postfix_myhostname }} is by default
#      defined as {{ fqdn }}.
mail_default_domain: mail.law-orga.de


# See `/doc/dns/dkim.md`.
mail_opendkim_key_selector: 2022-12.law-orga
...
