---
tls_acme_static_dir: /usr/local/lib/tls-acme
tls_acme_script_path: '{{ tls_acme_static_dir }}/update.bash'

tls_acme_config_dir: /usr/local/etc/tls-acme
tls_acme_config_file_path: /usr/local/etc/tls-acme/config.bash
tls_acme_accountkey_path: '{{ tls_acme_config_dir }}/account-key.pem'
tls_acme_accountkey_rsa_bits: 4096

tls_acme_data_dir: /var/local/tls-acme
tls_acme_data_staging_dir: '{{ tls_acme_data_dir }}/staging'

tls_acme_challenge_dir: /var/www/acme-challenges
...
