---
pkgs_base_system_other: '{{ (pkgs_base_system_other_standard + pkgs_base_system_other_extra) | unique | list }}'

# System packages - Important, but not necessary ones.
pkgs_base_system_other_standard:
  - apparmor
  
  # Package desc.:
  #  * "... necessary infrastructure for basic TCP/IP based networking.",
  #  * "... supplies ... /etc/services, /etc/rpc, /etc/protocols and
  #    /etc/ethertypes."
  - netbase

  # Recommended by: initramfs-tools-core (transitive dep. of kernel package)
  #  - This gives us the busybox tools in the initramfs.
  #    - Useful in case booting fails at initramfs stage.
  - busybox

  # Recommended by: initramfs-tools-core (transitive dep. of kernel package)
  #  - This should decrease the initrd size and/or speed up its
  #    [de-]compression.
  #  - Until Debian 11, pigz was "Recommended" instead.
  - zstd

  # Rotate log files.
  - logrotate

  # Notes:
  #  * Some packages need this for proper logging.
  #    - [citation needed]
  #  * I previously thought this was necessary for Postfix.
  #    - This does not seem to be the case (anymore?, since Debian 12?).
  #  * This is notably useful to get the mail logs centralized to `mail.log`,
  #    and with nice syntax highlighting in vim.
  #    - Compare `journalctl --facility mail`.
  #  * If used together with systemd-journald, this should at least double the
  #    size of storage used for logs.
  - rsyslog

  # Some packages install cron jobs that would otherwise never be executed.
  - cron
...
