---
pkgs_base_system_other: '{{ pkgs_base_system_other_standard + pkgs_base_system_other_extra | unique }}'

# System packages - Important, but not necessary ones.
pkgs_base_system_other_standard:
  - apparmor
  
  # Package desc.:
  #  * "... necessary infrastructure for basic TCP/IP based networking.",
  #  * "... supplies ... /etc/services, /etc/rpc, /etc/protocols and
  #    /etc/ethertypes."
  - netbase

  # Recommended by: initramfs-tools-core (transitive dep. of kernel package)
  #  - This gives us the busybox tools in the initramfs.
  #    - Useful in case booting fails at initramfs stage.
  - busybox

  # Recommended by: initramfs-tools-core (transitive dep. of kernel package)
  #  - This should decrease the initrd size and/or speed up its
  #    [de-]compression.
  #  - Until Debian 11, pigz was "Recommended" instead.
  - zstd

  # Rotate log files.
  - logrotate

  # Some packages need this for proper logging.
  #  - Notably, `postfix`.
  #    - TODO: Check whether still true for Debian Bookworm.
  - rsyslog

  # Some packages install cron jobs that would otherwise never be executed.
  - cron
...
