---
- name: Reload Postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Hash static aliases
  ansible.builtin.command:
    argv:
      - postmap
      - 'hash:{{ mail_postfix_maps_dir }}/static-aliases'

- name: Hash static user identity map
  ansible.builtin.command:
    argv:
      - postmap
      - 'hash:{{ mail_postfix_maps_dir }}/id_static-users'


- name: Reload OpenDKIM
  ansible.builtin.service:
    name: opendkim
    state: reloaded
...
