# /etc/bash.bashrc
#
# Partially taken from Debian's default `bash.bashrc'.


# If not running interactively, don't do anything.
# This should not really be needed--this file should only be sourced if bash is
# run interactively.  However, both Debian and Parabola add this check.
[[ "$-" =~ i ]] || return


# Update LINES and COLUMNS after each external command.
#  - Note: This is enabled by default, in bash.
shopt -s checkwinsize


# PS1
# See <https://misc.flogisoft.com/bash/tip_colors_and_formatting> on colors.
# Note: other shells may have other ways of coloring (e.g., OpenBSD's ksh).
if [ "`id -u`" -eq 0 ]
then
	PS1=$'\[\e[0;1;31m\]\u\[\e[30m\]@\[\e[36m\]\h\[\e[33m\] \W \[\e[31m\]#\[\e[0m\] '
else
	PS1=$'\[\e[0;1;32m\]\u\[\e[90m\]@\[\e[36m\]\h\[\e[33m\] \W \[\e[32m\]$\[\e[0m\] '
fi


# Bash completion.
#  * Bash completion, in Debian, is performed by the here-sourced file.
#    * Sourcing from /etc/profile is insufficient; that only happens for
#      login shells.
#    * There is no harm in sourcing it twice; the script checks for being
#      sourced twice (or so it claims; it relies upon another sourced script
#      for that).
#  * This ignores `/etc/bash_completion`.
#    * By default (on Debian) this just sources
#      `/usr/share/bash-completion/bash_completion`, like the below sourced
#      script.
. /etc/profile.d/bash_completion.sh


# History.
shopt -s histappend     # Do not overwrite history file (useful for >1 shells).
HISTCONTROL=ignoreboth  # equivalent to `ignorespace:ignoredups'.
HISTSIZE=-1             # Unlimited.
HISTFILESIZE=-1         # Unlimited.


# Globbing.
shopt -s globasciiranges globstar extglob globskipdots

# Do not let `source' use PATH.
shopt -u sourcepath

# Print an error message upon `shift`-ing "too far" (it returns nonzero
# regardless).
shopt -s shift_verbose


if [ -d /etc/bash.bashrc.d ]
then
	for i in /etc/bash.bashrc.d/*.bash
	do
		. "$i"
	done
	unset i
fi
