---
all:
  hosts:
    lawandorga-mail-server:
      ansible_host: '{{ network.primary.ipv4.address }}'
      network:
        primary:
          interface_name: ens2
          ipv4:
            # Note:
            #  * IPv4 address configuration is done via DHCP.
            #    * We do not love this.
            #    * Reason: The gateway is assumed not to be static.
            #    * Alternatively, we could arrange for only the gateway to be
            #      obtained via DHCP.
            address: '51.15.218.231'

        # See `/doc/database.md`.
        private_db:
          interface_name: ens5
          ipv4:
            address: 172.16.0.3
            mask_length: 24
            db:
              address: 172.16.0.2
              port: 5432

      hostname: '{{ inventory_hostname }}'

  vars:
    # We have a read-only `/`.
    ansible_remote_tmp: /tmp/ansible
    #ansible_ssh_pipelining: true       # Might also suffice.

mailservers:
  hosts:
    lawandorga-mail-server:
...
