---
all:
  hosts:
    lawandorga-mail-server:
      ansible_host: '{{ ip.ipv4.address }}'
      ip:
        interface_name: ens2
        ipv4:
          # This is the IP address of the NAT, we get a private address via
          # DHCP.
          address: '51.15.218.231'
        ipv6:
          address: '2001:bc8:47a0:1015::1'
          gateway_address: '2001:bc8:47a0:1015::'
          prefix_size: 64
      hostname: '{{ inventory_hostname }}'

  vars:
    # We have a read-only `/`.
    ansible_remote_tmp: /tmp/ansible
    #ansible_ssh_pipelining: true       # Might also suffice.

mailservers:
  hosts:
    lawandorga-mail-server:
...
