---
- name: Apply mail server configuration
  hosts: mailservers
  remote_user: root
  gather_facts: false


  roles:
    - common
    - backup
    - mail


  # Remount readonly filesystems (notably, the root filesysem).
  #  - Due to the readonly filesystems, we have to remount them read-write
  #    before any modification can be made.
  #  - Ideally, we'd only do the remount once necessary, but I do not know how
  #    to easily do that.
  #  - Instead, we remount the filesystems read-write before any task and
  #    remount it read-only after the last task.
  #  - NOTE: The final read-only remounting does not happen if any previous
  #    task fails.

  pre_tasks:
    - ansible.builtin.include_tasks: tasks/remount-rw.yaml
  post_tasks:
    - ansible.builtin.include_tasks: tasks/remount-ro.yaml
...
