---
web_app_mail_keyconfig_path: /etc/roundcube/key.conf.php

# Attachment/upload size limit.
#  - This is related to the message size limit.
#  - Due to base64 encoding and metadata, attachments must be notably
#    smaller than the message size limit.
#  - For simplicity, we use half of the message size limit.
#    - This should safely avoid the case were a single max-size attachment
#      causes the message size limit to be broken, while remaining reasonably
#      high.
web_app_mail_attachment_size_limit:
  '{{ ((mail_postfix_message_size_limit | int) / 2) | int }}'

# In some cases, we need to allow a little more than the attachment size limit.
#  - Choose 1 MiB.
web_app_mail_attachment_size_limit_plus_margin:
  '{{ (web_app_mail_attachment_size_limit | int) + (2 | pow(20) | int) }}'

# This should be set sufficiently high to allow for big uploads over slow
# connections.
web_app_mail_php_max_execution_time_seconds: 120

web_app_mail_php_version:
  '{{ web_app_mail_php_version_command.stdout }}'

# Note:
#  * This directory is managed by tempfiles.d(5).
#    - See `../templates/upload-tmpdir.tmpfiles.conf.j2`.
#    - It is regularly cleaned by tmpfiles.d(5), so does not need to be below
#      a common tmpdir, such as `/tmp`.
web_app_mail_upload_tmp_dir:
  '/tmp/php-upload'

web_app_mail_script_dir: /usr/local/lib/webmail

web_app_mail_delete_old_userdata_script_path:
  '{{ web_app_mail_script_dir }}/delete-old-userdata.bash'

# Note that we do not install this script ourselves.
#  - Thus, this variable should generally not be changed.
web_app_mail_rc_deluser_script_path:
  '/usr/share/roundcube/bin/deluser.sh'


# See also
#  - `/ansible/roles/mail/delete-old-userdata/templates/delete-old-userdata.bash.j2#get_dirs_from_db()`.
#  - `/ansible/roles/web/app/mail/templates/delete-old-userdata.bash.j2#_psql()`
#  * TODO: Deduplicate code.
web_app_mail_psql_argv:
  - psql
  - '--host={{ database_server_address }}'
  - '--port={{ database_server_port }}'
  - '--dbname={{ database_name_webmail }}'
  - '--username={{ database_user }}'
  - '--no-password'
  - '--no-psqlrc'
  - '--no-readline'
  - '--set=ON_ERROR_STOP=on'
  - '--echo-errors'
  - '--quiet'
  - '--tuples-only'
  - '--no-align'
...
